/**
 * VeoTransition Composition
 * Composición VeoTransition
 * 
 * Main Remotion composition for displaying AI-generated video transitions
 * Composición principal de Remotion para mostrar transiciones de video generadas por IA
 */

import React from 'react';
import { AbsoluteFill, Video, Audio, useCurrentFrame, useVideoConfig, interpolate } from 'remotion';
import type { VeoTransitionProps } from '../types';

/**
 * VeoTransition Component
 * Componente VeoTransition
 * 
 * Displays a video generated by Veo 3.1 with optional audio and effects
 * Muestra un video generado por Veo 3.1 con audio y efectos opcionales
 * 
 * @param props - Component props / Props del componente
 */
export const VeoTransition: React.FC<VeoTransitionProps> = ({
    videoUrl,
    audioUrl,
    title,
    loop = false,
}) => {
    const frame = useCurrentFrame();
    const { fps, durationInFrames } = useVideoConfig();

    // Fade in/out effect / Efecto de fade in/out
    const fadeInDuration = fps * 0.5; // 0.5 seconds
    const fadeOutStart = durationInFrames - fadeInDuration;

    const opacity = interpolate(
        frame,
        [0, fadeInDuration, fadeOutStart, durationInFrames],
        [0, 1, 1, 0],
        {
            extrapolateLeft: 'clamp',
            extrapolateRight: 'clamp',
        }
    );

    return (
        <AbsoluteFill style={{ backgroundColor: '#000' }}>
            {/* Main video / Video principal */}
            <AbsoluteFill style={{ opacity }}>
                <Video
                    src={videoUrl}
                    loop={loop}
                    style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                    }}
                />
            </AbsoluteFill>

            {/* Audio if provided / Audio si se proporciona */}
            {audioUrl && (
                <Audio src={audioUrl} />
            )}

            {/* Title overlay / Superposición de título */}
            {title && (
                <AbsoluteFill
                    style={{
                        justifyContent: 'flex-end',
                        alignItems: 'center',
                        padding: 40,
                    }}
                >
                    <div
                        style={{
                            backgroundColor: 'rgba(0, 0, 0, 0.7)',
                            padding: '20px 40px',
                            borderRadius: 10,
                            opacity,
                        }}
                    >
                        <h1
                            style={{
                                color: '#fff',
                                fontSize: 48,
                                fontWeight: 'bold',
                                margin: 0,
                                textAlign: 'center',
                            }}
                        >
                            {title}
                        </h1>
                    </div>
                </AbsoluteFill>
            )}
        </AbsoluteFill>
    );
};
